language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - echo "testfile" > FeedTheMonkey-123.AppImage
  - curl -F "file=@$(echo FeedTheMonkey*.AppImage)" https://file.io
  - curl https://google.com
