language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - echo "testfile" > FeedTheMonkey-123.AppImage
  - curl -H "Accept: application/json" -F "file=@$(echo FeedTheMonkey*.AppImage)" https://file.io
