language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - echo "testfile" > FeedTheMonkey-123.AppImage
  - curl -w "%{http_code}\n" -F "file=@$(echo FeedTheMonkey*.AppImage)" https://file.io -o /dev/null
  - curl https://google.com
